# Change these first
owner: Clickpoints # Your GitHub organization or username, where this repository lives
repo: uptime-monitoring # The name of this repository

sites:
  - name: S01-CPUK-GRA
    url: https://s01.cloud.clkpts.uk
  - name: S02-CPUK-LON
    url: https://s02.cloud.clkpts.uk
  - name: S03-CPUK-SBG
    url: https://s03.cloud.clkpts.co.uk
  - name: S04-CPUK-LON
    url: https://s04.cloud.clkpts.co.uk
  - name: S05-CPUK-LON
    url: https://s05.cloud.clkpts.co.uk
  - name: S01-INT
    url: http://s01.office.clkpts.co.uk/
  - name: S01-TDNL-BGM
    url: https://topdevelop.xyz
  - name: S02-AGSW-LON
    url: https://s02.all-green.co.uk
  - name: S03-AGSW-LON
    url: https://s03.all-green.co.uk
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.cloud.clkpts.co.uk
  # baseUrl: /your-repo-name
  logoUrl: https://clkpts.uk/res/img/wordmark-black.png
  name: CP (UKI) - Uptime Monitoring
  theme: light
  navbar:
    - title: Status
      href: /
      
  workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
